version: '3'
services:
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
    - "25"
    env_file:
      - ./credentials-smtp.env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"

networks:
  default:
    external:
      name: nginx-proxy
