version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-conf:/etc/nginx/conf.d
      - ./mod.conf:/etc/nginx/conf.d/mod.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock/:ro
      - nginx-conf:/etc/nginx/conf.d
      - ./mod.conf:/etc/nginx/conf.d/mod.conf
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:

networks:
  default:
    external:
     name: nginx-proxy

